package arielmessing.ebird.api.observations;

public record Observation (
    String speciesCode,
    String comName,
    String sciName,
    String locId,
    String locName,
    String obsDt,
    int howMany,
    double lat,
    double lng,
    boolean obsValid,
    boolean obsReviewed,
    boolean locationPrivate,
    String subId,
    String exoticCategory,
    String subnational2Code,
    String subnational2Name,
    String subnational1Code,
    String subnational1Name,
    String countryCode,
    String countryName,
    String userDisplayName,
    String obsId,
    String checklistId,
    boolean presenceNoted,
    boolean hasComments,
    boolean hasRichMedia,
    String evidence,
    String firstName,
    String lastName) { }